# Generated by Django 5.0.6 on 2024-11-08 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.TextField(default='abc123', max_length=32, primary_key=True, serialize=False)),
                ('last_heard', models.DateTimeField()),
                ('host', models.GenericIPAddressField(default='127.0.0.1')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_type', models.CharField(choices=[('ls', 'List Files')], max_length=32, verbose_name='Command Type')),
                ('cmd_args', models.CharField(max_length=1024, verbose_name='Command Arguments')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.agent')),
            ],
        ),
        migrations.CreateModel(
            name='CommandResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_output', models.CharField(max_length=1024, verbose_name='Command Output')),
                ('cmd_error', models.CharField(max_length=1024, verbose_name='Command Error')),
                ('cmd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.command', verbose_name='Command ID')),
            ],
        ),
    ]
