# Generated by Django 5.0.6 on 2024-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('last_heard', models.DateTimeField()),
            ],
        ),
    ]
