# Generated by Django 5.0.6 on 2024-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
