# Generated by Django 5.0.6 on 2024-09-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_agent_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_txt', models.CharField(max_length=1024)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.agent')),
            ],
        ),
    ]
